import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

/* ─────────────────────────────────────────────────────────────────────────────
   Fonts  (next/font – auto-optimised, no layout shift)
───────────────────────────────────────────────────────────────────────────── */
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

/* ─────────────────────────────────────────────────────────────────────────────
   Site constants  (single source of truth)
───────────────────────────────────────────────────────────────────────────── */
const BASE_URL =
  process.env.NEXT_PUBLIC_BASE_URL ?? "https://nexusai-gg-beta.vercel.app";

const APP_NAME        = "NEXUS AI";
const APP_SHORT_NAME  = "NEXUS";
const APP_DESCRIPTION =
  "The most advanced AI assistant for Roblox developers. Write Lua, debug scripts, build GUIs, and inject directly into Roblox Studio.";
const APP_TAGLINE     =
  "Write Lua · Debug Scripts · Build GUIs · Inject into Studio";
const APP_AUTHOR      = "NEXUS STUDIO";
const APP_EMAIL       = "support@nexusai.gg";          // update if needed
const TWITTER_HANDLE  = "@nexusstudio";
const DISCORD_URL     = "https://discord.gg/FzAF48mvK5";
const THEME_COLOR     = "#030312";
const ACCENT_COLOR    = "#00e5ff";

/* ─────────────────────────────────────────────────────────────────────────────
   Keywords  (comprehensive for SEO)
───────────────────────────────────────────────────────────────────────────── */
const KEYWORDS = [
  // Brand
  "NEXUS AI", "NEXUS STUDIO", "nexusai.gg",
  // Product
  "Roblox AI", "Roblox developer AI", "Roblox Studio AI",
  "Lua AI assistant", "Roblox script generator", "AI for Roblox",
  // Features
  "Roblox Lua code", "Roblox GUI builder", "Roblox DataStore",
  "Roblox Studio plugin", "Roblox script injection", "Roblox AI chat",
  "Roblox Studio plugin AI", "Roblox game development AI",
  // Competitors / alt search terms
  "AI coding assistant Roblox", "ChatGPT for Roblox",
  "Roblox scripting tool", "Lua code generator",
  // Long-tail
  "how to script in Roblox with AI", "AI assistant for Roblox developers",
  "write Roblox scripts with AI", "debug Roblox scripts automatically",
];

/* ─────────────────────────────────────────────────────────────────────────────
   Metadata Export  (used by Next.js for <head> generation)
───────────────────────────────────────────────────────────────────────────── */
export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),

  /* ── Titles ─────────────────────────────────────────────────────────── */
  title: {
    default:  `${APP_NAME} — Roblox Dev Intelligence`,
    template: `%s | ${APP_NAME}`,
  },

  /* ── Core ───────────────────────────────────────────────────────────── */
  description:      APP_DESCRIPTION,
  applicationName:  APP_NAME,
  category:         "developer tools",
  creator:          APP_AUTHOR,
  publisher:        APP_AUTHOR,
  authors:          [{ name: APP_AUTHOR, url: BASE_URL }],
  generator:        "Next.js",
  referrer:         "origin-when-cross-origin",

  keywords: KEYWORDS,

  /* ── Canonical / Alternates ─────────────────────────────────────────── */
  alternates: {
    canonical: BASE_URL,
    languages: {
      "en-US": BASE_URL,
      "id-ID": `${BASE_URL}/id`,   // Indonesian locale (if you add it)
    },
  },

  /* ── Robots ─────────────────────────────────────────────────────────── */
  robots: {
    index:               true,
    follow:              true,
    nocache:             false,
    googleBot: {
      index:                  true,
      follow:                 true,
      noimageindex:           false,
      "max-video-preview":    -1,
      "max-image-preview":    "large",
      "max-snippet":          -1,
    },
  },

  /* ── Open Graph (Facebook, LinkedIn, Discord, Telegram, WhatsApp) ───── */
  openGraph: {
    type:        "website",
    url:         BASE_URL,
    siteName:    APP_NAME,
    locale:      "en_US",
    title:       `${APP_NAME} — Roblox Dev Intelligence`,
    description: APP_TAGLINE,
    images: [
      /* Primary 1200×630 – used by most platforms */
      {
        url:    "/og-image.png",          // generated by app/opengraph-image.tsx
        width:  1200,
        height: 630,
        alt:    `${APP_NAME} — Roblox Dev Intelligence`,
        type:   "image/png",
      },
      /* Square fallback 1:1 – used by some mobile clients */
      {
        url:    "/og-image-square.png",   // generated by app/opengraph-image-square.tsx
        width:  600,
        height: 600,
        alt:    `${APP_NAME}`,
        type:   "image/png",
      },
    ],
  },

  /* ── Twitter / X Card ───────────────────────────────────────────────── */
  twitter: {
    card:        "summary_large_image",
    site:        TWITTER_HANDLE,
    creator:     TWITTER_HANDLE,
    title:       `${APP_NAME} — Roblox Dev Intelligence`,
    description: `The most advanced AI assistant for Roblox developers. ${APP_TAGLINE}.`,
    images: [
      {
        url:    "/twitter-image.png",     // generated by app/twitter-image.tsx
        width:  1200,
        height: 628,
        alt:    `${APP_NAME} — Roblox Dev Intelligence`,
      },
    ],
  },

  /* ── App Links (deep-linking) ───────────────────────────────────────── */
  appLinks: {
    web: {
      url:          BASE_URL,
      should_fallback: false,
    },
  },

  /* ── Icons ──────────────────────────────────────────────────────────── */
  icons: {
    icon: [
      { url: "/favicon.ico",    sizes: "any" },
      { url: "/icon-16.png",    type: "image/png", sizes: "16x16"   },
      { url: "/icon-32.png",    type: "image/png", sizes: "32x32"   },
      { url: "/icon-48.png",    type: "image/png", sizes: "48x48"   },
      { url: "/icon-96.png",    type: "image/png", sizes: "96x96"   },
      { url: "/icon-192.png",   type: "image/png", sizes: "192x192" },
      { url: "/icon-512.png",   type: "image/png", sizes: "512x512" },
      { url: "/icon.svg",       type: "image/svg+xml"                },
    ],
    apple: [
      { url: "/apple-touch-icon.png",        sizes: "180x180" },
      { url: "/apple-touch-icon-152.png",    sizes: "152x152" },
      { url: "/apple-touch-icon-120.png",    sizes: "120x120" },
    ],
    shortcut: "/favicon.ico",
    other: [
      /* Used by some browsers & PWA launchers */
      { rel: "mask-icon",       url: "/safari-pinned-tab.svg", color: ACCENT_COLOR },
      { rel: "msapplication-TileImage", url: "/icon-192.png"  },
    ],
  },

  /* ── PWA / Web App Manifest ─────────────────────────────────────────── */
  manifest: "/manifest.json",

  /* ── Verification tags (add your own codes from Search Console, etc.) ─ */
  verification: {
    google:    process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFY  ?? "",
    yandex:    process.env.NEXT_PUBLIC_YANDEX_VERIFY       ?? "",
    // bing & others via `other` below
  },

  /* ── Other / Misc head tags ─────────────────────────────────────────── */
  other: {
    /* Bing / Microsoft Clarity */
    "msvalidate.01":       process.env.NEXT_PUBLIC_BING_VERIFY ?? "",
    /* Force HTTPS referral */
    "referrer":            "strict-origin-when-cross-origin",
    /* Discord embed accent */
    "theme-color":         THEME_COLOR,
    /* Telegram open-in-browser hint */
    "telegram:channel":    DISCORD_URL,
    /* Apple mobile web app */
    "apple-mobile-web-app-capable":           "yes",
    "apple-mobile-web-app-status-bar-style":  "black-translucent",
    "apple-mobile-web-app-title":             APP_SHORT_NAME,
    /* Microsoft IE/Edge legacy */
    "msapplication-TileColor":                THEME_COLOR,
    "msapplication-config":                   "/browserconfig.xml",
    /* Format detection: disable auto-phone-link on iOS */
    "format-detection":    "telephone=no",
    /* Prevent content sniffing */
    "X-Content-Type-Options": "nosniff",
  },
};

/* ─────────────────────────────────────────────────────────────────────────────
   Viewport  (Next.js 14+ requires separate export)
───────────────────────────────────────────────────────────────────────────── */
export const viewport: Viewport = {
  width:                "device-width",
  initialScale:         1,
  maximumScale:         5,          // allow pinch-zoom for accessibility
  userScalable:         true,
  colorScheme:          "dark",
  themeColor: [
    { media: "(prefers-color-scheme: dark)",  color: THEME_COLOR },
    { media: "(prefers-color-scheme: light)", color: THEME_COLOR },
  ],
};

/* ─────────────────────────────────────────────────────────────────────────────
   JSON-LD Structured Data
   Multiple schemas for richer Google results (SoftwareApp + Organization + FAQ)
───────────────────────────────────────────────────────────────────────────── */
const jsonLdSchemas = [
  /* SoftwareApplication – shows ratings, category in Google */
  {
    "@context": "https://schema.org",
    "@type":    "SoftwareApplication",
    "@id":      `${BASE_URL}/#software`,
    name:                APP_NAME,
    applicationCategory: "DeveloperApplication",
    operatingSystem:     "Web, Windows, macOS, Linux",
    description:         APP_DESCRIPTION,
    url:                 BASE_URL,
    image:               `${BASE_URL}/og-image.png`,
    author: {
      "@type": "Organization",
      name:    APP_AUTHOR,
      url:     BASE_URL,
      email:   APP_EMAIL,
      sameAs:  [DISCORD_URL, `https://twitter.com/${TWITTER_HANDLE.replace("@","")}`],
    },
    offers: {
      "@type":         "Offer",
      price:           "0",
      priceCurrency:   "USD",
      availability:    "https://schema.org/InStock",
      description:     "Free tier available. Pro plan with more credits.",
    },
    featureList: [
      "Lua code generation for Roblox",
      "Roblox Studio plugin injection",
      "GUI builder with AI",
      "DataStore design",
      "Script debugging",
      "Multi-model AI support",
    ],
    screenshot: `${BASE_URL}/og-image.png`,
    softwareVersion: "2.0",
    releaseNotes:    `${BASE_URL}/changelog`,
  },

  /* Organization – helps Google show a Knowledge Panel */
  {
    "@context": "https://schema.org",
    "@type":    "Organization",
    "@id":      `${BASE_URL}/#organization`,
    name:        APP_AUTHOR,
    url:         BASE_URL,
    logo: {
      "@type": "ImageObject",
      url:     `${BASE_URL}/icon-512.png`,
      width:   512,
      height:  512,
    },
    image:       `${BASE_URL}/og-image.png`,
    description: `${APP_AUTHOR} builds AI-powered developer tools for Roblox game creators.`,
    sameAs: [
      DISCORD_URL,
      `https://twitter.com/${TWITTER_HANDLE.replace("@","")}`,
      `https://www.youtube.com/@nexusstudio`,
      `https://create.roblox.com/store/asset/91870814099475/NEXUS-AI`,
    ],
    contactPoint: {
      "@type":            "ContactPoint",
      contactType:        "customer support",
      availableLanguage:  ["English", "Indonesian"],
      url:                DISCORD_URL,
    },
  },

  /* WebSite – enables Google's Sitelinks searchbox */
  {
    "@context": "https://schema.org",
    "@type":    "WebSite",
    "@id":      `${BASE_URL}/#website`,
    url:         BASE_URL,
    name:        APP_NAME,
    description: APP_DESCRIPTION,
    publisher: { "@id": `${BASE_URL}/#organization` },
    potentialAction: {
      "@type":       "SearchAction",
      target: {
        "@type":     "EntryPoint",
        urlTemplate: `${BASE_URL}/search?q={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
    inLanguage: ["en-US", "id-ID"],
  },

  /* FAQPage – shows expandable Q&A directly in Google results */
  {
    "@context": "https://schema.org",
    "@type":    "FAQPage",
    mainEntity: [
      {
        "@type":          "Question",
        name:             "What is NEXUS AI?",
        acceptedAnswer: {
          "@type": "Answer",
          text:    "NEXUS AI is an advanced AI assistant for Roblox developers. It can write Lua scripts, debug code, build GUIs, and inject code directly into Roblox Studio via a plugin.",
        },
      },
      {
        "@type":          "Question",
        name:             "Is NEXUS AI free to use?",
        acceptedAnswer: {
          "@type": "Answer",
          text:    "Yes. NEXUS AI offers a free plan with 30 credits to start. You can earn 2 free credits every day, or upgrade to Pro for 25 credits per day and higher limits.",
        },
      },
      {
        "@type":          "Question",
        name:             "How does the Roblox Studio plugin work?",
        acceptedAnswer: {
          "@type": "Answer",
          text:    "Install the NEXUS AI plugin from the Roblox Creator Store, enable HTTP Requests and Script Injection in Studio settings, then click CONNECT in the toolbar. Once connected, AI-generated scripts are injected directly into your game.",
        },
      },
      {
        "@type":          "Question",
        name:             "Which AI models does NEXUS AI use?",
        acceptedAnswer: {
          "@type": "Answer",
          text:    "NEXUS AI supports multiple models including Gemini 2.5 Flash, Claude 3.5, and more. You can switch models mid-conversation from the input bar.",
        },
      },
      {
        "@type":          "Question",
        name:             "Does NEXUS AI support Indonesian language?",
        acceptedAnswer: {
          "@type": "Answer",
          text:    "Yes. NEXUS AI supports both English and Bahasa Indonesia. You can change the language from Settings in the sidebar.",
        },
      },
    ],
  },
];

/* ─────────────────────────────────────────────────────────────────────────────
   Root Layout
───────────────────────────────────────────────────────────────────────────── */
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${inter.variable} ${jetbrainsMono.variable}`}
        suppressHydrationWarning
      >
        <head>
          {/* ── JSON-LD Structured Data (multiple schemas) ── */}
          {jsonLdSchemas.map((schema, i) => (
            <script
              key={i}
              type="application/ld+json"
              dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
            />
          ))}

          {/* ── Preconnect to critical third-party origins ── */}
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
          <link rel="preconnect" href="https://www.roblox.com" />
          <link rel="preconnect" href="https://cdnjs.cloudflare.com" />

          {/* ── DNS prefetch for other assets ── */}
          <link rel="dns-prefetch" href="https://cdn.jsdelivr.net" />
          <link rel="dns-prefetch" href="https://challenges.cloudflare.com" />

          {/* ── Browserconfig for Windows tiles ── */}
          <meta name="msapplication-config" content="/browserconfig.xml" />
          <meta name="msapplication-TileColor" content="#030312" />
          <meta name="msapplication-TileImage" content="/icon-192.png" />

          {/* ── Safari Pinned Tab ── */}
          <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#00e5ff" />

          {/* ── Canonical (belt-and-suspenders alongside metadata) ── */}
          <link rel="canonical" href={BASE_URL} />
        </head>

        <body suppressHydrationWarning>
          {children}

          {/* ── Vercel observability ── */}
          <Analytics />
          <SpeedInsights />
        </body>
      </html>
    </ClerkProvider>
  );
}